"""Custom tools for the multi-agent demo."""

from langchain_core.tools import tool


@tool
def calculate(operation: str, a: float, b: float) -> float:
    """Perform a mathematical calculation.

    Args:
        operation: The operation to perform (add, subtract, multiply, divide)
        a: First number
        b: Second number

    Returns:
        The result of the calculation
    """
    if operation == "add":
        return a + b
    elif operation == "subtract":
        return a - b
    elif operation == "multiply":
        return a * b
    elif operation == "divide":
        if b == 0:
            return "Error: Division by zero"
        return a / b
    else:
        return f"Error: Unknown operation '{operation}'"


@tool
def generate_report(title: str, content: str) -> str:
    """Generate a formatted report.

    Args:
        title: The report title
        content: The main content

    Returns:
        A formatted report string
    """
    return f"""
# {title}

## Summary
{content}

---
*Generated by deepagents multi-agent system*
"""
